"""FastAPI app instance and routes"""

"""Client request → FastAPI parses it against Pydantic model → 
validation passes → validated data goes into the route function → 
you build an ORM model object from it → SQLAlchemy session sends it to Postgres."""


from database import Base, engine
from models import SleepReadingDB  # must be imported so Base knows about it
from database import SessionLocal


# Creates all tables registered with Base.metadata if they don't already exist.
# Safe to run every time the app starts — it's idempotent and won't recreate
# or duplicate existing tables.
Base.metadata.create_all(bind=engine)

db = SessionLocal()
new_reading = SleepReadingDB(
    patient_id=5,
    sleep_duration_hours=7.5,
    heart_rate=62.0,
    is_deep_sleep=True,
    raw_device_data={"device": "OuraRing", "battery": 84}
)

"""db.add(new_reading)
db.commit()
db.refresh(new_reading)
print(new_reading.id)  # auto-generated by Postgres, now available"""

# Get all readings
all_readings = db.query(SleepReadingDB).all()
print(all_readings)

# Get one by id
one_reading = db.query(SleepReadingDB).filter(SleepReadingDB.id == 1).first()
print(one_reading)

# Get with a condition
long_sleep = db.query(SleepReadingDB).filter(SleepReadingDB.sleep_duration_hours > 7).all()
print(long_sleep)

